import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import SideNav from "../components/navbar/SideNav";
import Header from "../components/navbar/HeaderMain";
import HeaderMobile from "../components/navbar/HeaderMobile";
import WrapperPage from "../components/navbar/WrapperPage";
import WrapperMain from "../components/navbar/WrapperMain";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "shitstack",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white`}
      >
        <div className="flex">
          <SideNav />
          <main className="flex-1">
            <WrapperMain>
              <Header />
              <HeaderMobile />
              <WrapperPage>{children}</WrapperPage>
            </WrapperMain>
          </main>
        </div>
      </body>
    </html>
  );
}
