import type { Metadata } from "next";
import "./globals.css";
import SideNav from "../components/navbar/SideNav";
import HeaderMobile from "../components/navbar/HeaderMobile";
import WrapperPage from "../components/navbar/WrapperPage";
import WrapperMain from "../components/navbar/WrapperMain";
import HeaderMain from "../components/navbar/HeaderMain";

const currentDate = new Date();
const year = currentDate.getFullYear();

export const metadata: Metadata = {
  title: `madtoken © ${year}`,
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <HeaderMain />
        <HeaderMobile />
        <div className="flex">
          <SideNav />
          <main className="flex-1">
            <WrapperMain>
              <WrapperPage>{children}</WrapperPage>
            </WrapperMain>
          </main>
        </div>
      </body>
    </html>
  );
}
