import type { Metadata } from "next";
import "./globals.css";
import SideNav from "../components/navbar/SideNav";
import Header from "../components/navbar/HeaderMain";
import HeaderMobile from "../components/navbar/HeaderMobile";
import WrapperPage from "../components/navbar/WrapperPage";
import WrapperMain from "../components/navbar/WrapperMain";

export const metadata: Metadata = {
  title: "shitstack",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="flex">
          <SideNav />
          <main className="flex-1">
            <WrapperMain>
              <Header />
              <HeaderMobile />
              <WrapperPage>{children}</WrapperPage>
            </WrapperMain>
          </main>
        </div>
      </body>
    </html>
  );
}
